<?php

/**
 * @file
 * Install hooks for the backdrop_test_users module.
 */

/**
 * Implements hook_install().
 */
function backdrop_test_users_install() {
  // Add test users.
  backdrop_test_users_add_users();
}

/**
 * Implements hook_uninstall().
 */
function backdrop_test_users_uninstall() {
  // Delete created users.
  // Since they all have the same email, we can load them by that parameter.
  $uids = db_query("SELECT uid FROM {users} WHERE mail = 'noreply@nowhere.com'")->fetchCol();
  user_delete_multiple($uids);
}

/**
 * Creates users needed for test runs.
 */
function backdrop_test_users_add_users() {
  // List needed users.
  $users = array(
    'developer',
    'site_owner'
  );

  // Create users.
  foreach ($users as $user_name) {
    // For some reason, I ran into the issue where the same user was created multiple times.
    // If user exists, skip creation.
    if (user_load_by_name($user_name)) {
      continue;
    }

    // Get role ID.
    $role = user_role_load($user_name);
    $new_user = entity_create('user', array(
        'name' => $user_name,
        'pass' => $user_name,
        'mail' => 'noreply@nowhere.com',
        'status' => 1,
        'init' => 'noreply@nowhere.com',
        'roles' => array(
          $role->rid => $user_name,
        ),
      )
    );

    user_save($new_user);
  }
}
